server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**,/actuator/health
            - id: task-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/tasks/**
              filters:
                - name: AuthenticationFilter
            - id: calendar-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/calendar/**
              filters:
                - name: AuthenticationFilter
            - id: notification-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - AuthenticationFilter
            - id: notification-websocket
              uri: ws://localhost:8084
              predicates:
                - Path=/ws-notifications/**
              filters:
                - AuthenticationFilter
            - id: notification-preferences
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/notifications/user/*/preferences
              filters:
                - AuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always