server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**,/actuator/health
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
